POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli&grant_type=password&username=admin&password=123456

###
POST http://localhost:8080/auth/admin/realms/master/users/user/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWlZNZVdid2hFUFRsV2gyVmNzZzdIY3ZvcE5PaE1VSHlhc0Y1bE9UcTdNIn0.eyJqdGkiOiIyNTU0ZjYxMC05NGVlLTQ0NmItYmM5NC05MmYyNzE5ODdkMDEiLCJleHAiOjE1MjIwNTg0ODksIm5iZiI6MCwiaWF0IjoxNTIyMDU4NDI5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiYWRtaW4tY2xpIiwic3ViIjoiNmY5NjQxY2ItMGE0Zi00ODc5LTk0YmMtMDg2NWM3ZmQ2NmMxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiYmMxNmRhMWMtYjhlMi00YzllLTlhNGItZDBjOTdlMGJiMmUzIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6W10sInJlc291cmNlX2FjY2VzcyI6e30sInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.IntrrSxyN4dr9uOu1lxcb0BwrbDw-dMMcCRj0EtqNaJ4GO6OrcKzrK-PG50o4zBbrKlK5iekCiur8r7KokBuAt47qfjwWhqy7vmd9jMKNk3skyRZpFkJe6Ewx7cdgdopFLfQM8PZbfiYUsuCFba-oZF4m0XvPdEn438SzcoL4F3YAiSrFi16kYBEF8e1YrgKQDKArRWSW4GGuVcTHa5PUaFmxNijOg_8UG_rypVfWLNHEgkAIl6zGWhzwAejtALxgUwJONYDgMHlimYKK4ktp_K9c8cZPBC7wi1sSMj0r2Sr5Fxrr_OMcdm5IkOxIQS29urP9ZrBXIuh855p2WKtOA

###